export interface PlayerCard {
    name: string,
    rarity: string,
    set_name: string,
    thumbnail_url: string,
    team: string,
    lineup: boolean,
    edition: number,
    purchase: number,
    market: number,
    sale: number,
    offer: number,
    diff: number,
    link: string,
    event: any,
}
