# Set base image (host OS)
FROM --platform=linux/x86_64 python:3.9.5-slim

# By default, listen on port 5000
EXPOSE 5000/tcp

# Set the working directory in the container
WORKDIR /api

# Copy the dependencies file to the working directory
COPY ../api/requirements.txt .

# 
RUN pip install --upgrade pip setuptools wheel

RUN apt-get update \
    && apt-get -y install libpq-dev gcc

# Install any dependencies
RUN pip install -r requirements.txt

# Copy the content of the local src directory to the working directory
COPY ../api .

# Specify the command to run on container start
RUN chmod u+x ./entrypoint.sh
ENTRYPOINT ["./entrypoint.sh"]
# CMD [ "python", "-m", "app" ]
# CMD ["sleep", "1000"]